name: Update Major Version Tag

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*"
  release:
    types: [created]

permissions:
  contents: write

jobs:
  update-major-version-tag:
    name: Update Major Version Tag
    runs-on: ubuntu-latest
    steps:
      - name: Update Major Version Tag
        uses: cssnr/update-version-tags-action@v2
        with:
          tags: latest
